"""init lms schema

Revision ID: ad47f05fbe3d
Revises: 
Create Date: 2026-04-22 12:55:59.401740
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad47f05fbe3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mob_no', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('institute_id'),
    sa.UniqueConstraint('email', name='uq_institute_email')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name', name='uq_role_name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('institute_id', 'course_name', name='uq_course_name_institute')
    )
    op.create_index(op.f('ix_courses_institute_id'), 'courses', ['institute_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('default_institute_id', sa.String(length=36), nullable=True),
    sa.Column('allow_multi_tenant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_institute_id'], ['institutes.institute_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mob_no', sa.String(length=20), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_users_institute_id'), 'users', ['institute_id'], unique=False)
    op.create_table('auth',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subcourses',
    sa.Column('subcourse_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('subcourse_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.PrimaryKeyConstraint('subcourse_id'),
    sa.UniqueConstraint('course_id', 'subcourse_name', name='uq_subcourse_name_per_course')
    )
    op.create_index(op.f('ix_subcourses_institute_id'), 'subcourses', ['institute_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('subcourse_id', sa.String(length=36), nullable=False),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['subcourse_id'], ['subcourses.subcourse_id'], ),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('institute_id', 'batch_name', name='uq_batch_name_institute')
    )
    op.create_index(op.f('ix_batches_institute_id'), 'batches', ['institute_id'], unique=False)
    op.create_table('modules',
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('subcourse_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['subcourse_id'], ['subcourses.subcourse_id'], ),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('subcourse_id', 'module_name', name='uq_module_name_per_subcourse')
    )
    op.create_index(op.f('ix_modules_institute_id'), 'modules', ['institute_id'], unique=False)
    op.create_table('user_courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('subcourse_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['subcourse_id'], ['subcourses.subcourse_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', 'subcourse_id', name='uq_user_course')
    )
    op.create_index(op.f('ix_user_courses_institute_id'), 'user_courses', ['institute_id'], unique=False)
    op.create_table('user_selected_courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('subcourse_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['subcourse_id'], ['subcourses.subcourse_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', 'subcourse_id', name='uq_user_selected_course')
    )
    op.create_table('batch_teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'user_id', name='uq_batch_teacher')
    )
    op.create_index(op.f('ix_batch_teachers_institute_id'), 'batch_teachers', ['institute_id'], unique=False)
    op.create_table('contents',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_contents_institute_id'), 'contents', ['institute_id'], unique=False)
    op.create_table('user_batches',
    sa.Column('user_batch_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_batch_id'),
    sa.UniqueConstraint('user_id', 'batch_id', name='uq_user_batch')
    )
    op.create_index(op.f('ix_user_batches_institute_id'), 'user_batches', ['institute_id'], unique=False)
    op.create_table('user_modules',
    sa.Column('user_module_id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_module_id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module')
    )
    op.create_index(op.f('ix_user_modules_institute_id'), 'user_modules', ['institute_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institute_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_progress')
    )
    op.create_index(op.f('ix_user_progress_institute_id'), 'user_progress', ['institute_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_institute_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_modules_institute_id'), table_name='user_modules')
    op.drop_table('user_modules')
    op.drop_index(op.f('ix_user_batches_institute_id'), table_name='user_batches')
    op.drop_table('user_batches')
    op.drop_index(op.f('ix_contents_institute_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_batch_teachers_institute_id'), table_name='batch_teachers')
    op.drop_table('batch_teachers')
    op.drop_table('user_selected_courses')
    op.drop_index(op.f('ix_user_courses_institute_id'), table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_index(op.f('ix_modules_institute_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_batches_institute_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_subcourses_institute_id'), table_name='subcourses')
    op.drop_table('subcourses')
    op.drop_table('auth')
    op.drop_index(op.f('ix_users_institute_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_courses_institute_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('roles')
    op.drop_table('institutes')
    # ### end Alembic commands ###
